{% set name = "asgi-correlation-id" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/asgi_correlation_id-{{ version }}.tar.gz
  sha256: f66ea7ecc14c91a59d75e81c8e38f7b271f7ca429a479874e54f9e9f6bfaf713

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - pip
    - poetry >=0.12
  run:
    - python >=3.7,<4.0
    - starlette >=0.18

test:
  imports:
    - asgi_correlation_id
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/snok/asgi-correlation-id
  summary: Middleware correlating project logs to individual requests
  license: BSD-4-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sondrelg
    - ludaavics
